spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/metrics_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always

app:
  scheduler:
    flush-rate-ms: 5000